//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> author_id { get; set; }
        public string sub_title { get; set; }
        public string content_body { get; set; }
        public Nullable<System.DateTime> published_at { get; set; }
        public string image { get; set; }
    
        public virtual user user { get; set; }
    }
}
