//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_details
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name_on_card { get; set; }
        public Nullable<int> card_number { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<int> cvv { get; set; }
    
        public virtual user user { get; set; }
    }
}
