//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_addresses
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public string city { get; set; }
        public string state_or_province_or_region { get; set; }
        public Nullable<int> zip_or_postal_code { get; set; }
        public string country { get; set; }
    
        public virtual user user { get; set; }
    }
}
