//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Green_LeafEntities : DbContext
    {
        public Green_LeafEntities()
            : base("name=Green_LeafEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminTable> AdminTables { get; set; }
        public DbSet<Category_Tables> Category_Tables { get; set; }
        public DbSet<ProductTable> ProductTables { get; set; }
        public DbSet<Promotion_Table> Promotion_Table { get; set; }
        public DbSet<BlogTable> BlogTables { get; set; }
    }
}
